### ISSUE TITLE
Standardize the BERT embeddings dataset

### ISSUE THREAD

**Issue by AMOOOMA** [AMOOOMA/stocktwits-svm-nlp#13]
Standardize the current dataset into same length vectors using word n-grams for compressing and duplicate token vector for expanding

**Comment by dillydabi** [comment]
could you elaborate how you want it standardized here? Or is it up to whoever codes it

**Comment by AMOOOMA** [comment]
Some example are like: (note the strings represent their word embedding)

Standard length 10:
"["This", "is", "a", "message", "."]" -> "["This", "This", "is", "is", "a", "a", "message", "message", ".", "."]"

"[This is a very long message and exceeds 10 which is our standard length]", for this one we combine some of the token vectors by averaging them to get to length 10. for instance, "This",  "is" can be avg(This, is)

For the duplicate method you can duplicate how many word vector you want, but we want it to keep the original structure as much as possible. And for shrinking, you can avg how many tokens you like, but it's best to use an algorithm that keeps the original message structure as much as possible. So try avoid say duplicating the same word for 5 times  when the messages has 10 tokens and avoid averaging say the first half the messages and leave the second half etc. 

The detailed implementation plan is update to the coder, duplicating and averaging is just some methods to manipulating with word vectors.

**Comment by AMOOOMA** [comment]
Implemented, closed issue.
